InjectsenseCore/Controllers/ManageMyClinicController.cs
// ************************************************************
// Copyright (C) 2018 Injectsense, Inc. - All Rights Reserved
// ************************************************************
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Injectsense.Models;
using Injectsense.Helpers;
using Injectsense.DataAccess.Repositories;
using Injectsense.DataAccess.Entities;
using Injectsense.DataAccess;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using System.Security.Claims;

namespace Injectsense.Controllers
{
    [Authorize]
    [OutputCache(Duration = 0)]
    public class ManageMyClinicController : Controller
    {
        IUnitOfWork Transaction { get; }
        IClinicRepository ClinicRepository { get; }

        private readonly IServiceProvider Services;

        public ManageMyClinicController(IUnitOfWork unitOfWork, 
                                        IClinicRepository clinicRepository, 
                                        IServiceProvider services)
        {
            Transaction = unitOfWork;
            ClinicRepository = clinicRepository;

            Services = services;
        }

        // GET: ManageMyClinic
        public ActionResult Index()
        {
            MainContext mainContext = Services.GetRequiredService<MainContext>();

            ClaimsPrincipal currentUser = this.User;
            string currentUserName = currentUser.FindFirst(ClaimTypes.Name).Value;

            (Guid ClinicId, Guid ClinicStaffId, string ClinicName, string ClinicStaffFirstName, string ClinicStaffLastName) clinicInfo = ClinicStaffHelper.GetUsersClinicIdFromRequest(currentUserName, mainContext);

            ManageMyClinicModel model = new ManageMyClinicModel();
            model.Initialize(currentUserName, mainContext);

            PopulateModel(model);

            return View(model);
        }

        private void PopulateModel(ManageMyClinicModel model)
        {
            Clinic clinicInfo;

            try
            {
                clinicInfo = ClinicRepository.Find(x => x.Id == model.ClinicId).Single();
            }
            catch (Exception ex)
            {
                throw new Exception("Clinic Id not found.", ex);
            }
 
            model.ClinicNamePrimary = clinicInfo.NamePrimary;
            model.ClinicAddressLine1 = clinicInfo.AddressLine1;
            model.ClinicAddressLine2 = clinicInfo.AddressLine2;
            model.City = clinicInfo.City;
            model.State = clinicInfo.StateCode;
            model.Zipcode = clinicInfo.Zipcode;
            model.PhonePrimary = clinicInfo.PrimaryPhone;
            model.PrimaryContactFirstName = clinicInfo.PrimaryContactFirstName;
            model.PrimaryContactLastName = clinicInfo.PrimaryContactLastName;
            model.PrimaryContactEmailAddress = clinicInfo.PrimaryContactEmailAddress;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ManageMyClinicModel model)
        {
            // If the IsClinicProfile tab is true then the user has just posted
            // the Clinic Profile updates - so just focus on these fields for now
            // for validation and for saving to database.
            // If the IsClinicProfile tab is false then the user has just posted
            // the Primary Contact information.
            if (model.IsClinicProfileTab.ToLower().Equals("true"))
            {
                // The max string lengths are enforced in the view.
                if ((model.ClinicNamePrimary == null) || (model.ClinicNamePrimary.Length <= 0))
                {
                    ModelState.AddModelError("clinicNamePrimary", "Clinic Name is required.");
                }

                if ((model.ClinicAddressLine1 == null) || (model.ClinicAddressLine1.Length <= 0))
                {
                    ModelState.AddModelError("clinicAddressLine1", "Address is required.");
                }

                if ((model.City == null) || (model.City.Length <= 0))
                {
                    ModelState.AddModelError("city", "City is required.");
                }

                if ((model.State == null) || (model.State.Length <= 0))
                {
                    ModelState.AddModelError("state", "State is required.");
                }

                if ((model.Zipcode == null) || (model.Zipcode.Length <= 0))
                {
                    ModelState.AddModelError("zipcode", "Zipcode is required.");
                }
                else
                {
                    string pattern = @"^\d{5}$";
                    Regex zipcodeRegEx = new Regex(pattern, RegexOptions.IgnoreCase);
                    Match m = zipcodeRegEx.Match(model.Zipcode);
                    if (!m.Success)
                    {
                        ModelState.AddModelError("zipcode", "Zipcode is invalid.");
                    }
                }

                if ((model.PhonePrimary == null) || (model.PhonePrimary.Length <= 0))
                {
                    ModelState.AddModelError("phonePrimary", "Phone Number is required.");
                }
                else
                {
                    // Verify only digits have been entered for phone number.
                    string pattern = @"((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}";
                    Regex phoneNumberRegEx = new Regex(pattern, RegexOptions.IgnoreCase);
                    Match m = phoneNumberRegEx.Match(model.PhonePrimary);
                    if (!m.Success)
                    {
                        ModelState.AddModelError("phonePrimary", "Phone Number is invalid.");
                    }
                }
            }
            else
            {
                // The submit is the primary contact tab.
                // Just validate fields on the primary contact tab.
                if ((model.PrimaryContactFirstName == null) || (model.PrimaryContactFirstName.Length <= 0))
                {
                    ModelState.AddModelError("primaryContactFirstName", "First Name is required.");
                }

                if ((model.PrimaryContactLastName == null) ||(model.PrimaryContactLastName.Length <= 0))
                {
                    ModelState.AddModelError("primaryContactLastName", "Last Name is required.");
                }

                if ((model.PrimaryContactEmailAddress == null) || (model.PrimaryContactEmailAddress.Length <= 0))
                {
                    ModelState.AddModelError("primaryContactEmailAddress", "Email Address is required.");
                }
                else
                {
                    string pattern = @"(\w+?@\w+?\x2E.+)";
                    Regex emailRegEx = new Regex(pattern, RegexOptions.IgnoreCase);
                    Match m = emailRegEx.Match(model.PrimaryContactEmailAddress);
                    if (!m.Success)
                    {
                        ModelState.AddModelError("primaryContactEmailAddress", "Email Address is invalid.");
                    }
                }

            }


            if (ModelState.IsValid)
            {
                // Save and then re-populate the model and return to view.
                // Need to check the tab that is being edited and save based on that.
                Guid clinicId = Guid.Parse(model.ClinicIdString);

                if (model.IsClinicProfileTab.ToLower().Equals("true"))
                {
                    // FInd the clinic entity and save the specific fields that were available on form.
                    Clinic clinicEntity = ClinicRepository.Find(x => x.Id == clinicId).Single();

                    clinicEntity.NamePrimary = model.ClinicNamePrimary;
                    clinicEntity.AddressLine1 = model.ClinicAddressLine1;
                    clinicEntity.AddressLine2 = model.ClinicAddressLine2;
                    clinicEntity.City = model.City;
                    clinicEntity.StateCode = model.State;
                    clinicEntity.Zipcode = model.Zipcode;
                    clinicEntity.PrimaryPhone = model.PhonePrimary;

                    Transaction.Commit();
                }
                else
                {
                    // FInd the clinic entity and save the specific fields that were available on form.
                    Clinic clinicEntity = ClinicRepository.Find(x => x.Id == clinicId).Single();

                    clinicEntity.PrimaryContactFirstName = model.PrimaryContactFirstName;
                    clinicEntity.PrimaryContactLastName = model.PrimaryContactLastName;
                    clinicEntity.PrimaryContactEmailAddress = model.PrimaryContactEmailAddress;

                    Transaction.Commit();
                }

                    return RedirectToAction("Index");
            }
            else
            {
                // The model is returned here which may have invalid values entered and error statuses.
                return View(model);
            }
        }

        public ActionResult LogOut()
        {
            // This action/method is a kludge because I couldn't get the "sign out" link to change form Home/Logout to Account/Logout.
            // So this method is located here to call the LogOut action on the AccountController.

            // TODO: Remove after successful port to ASP.NET core.
            //var controller = DependencyResolver.Current.GetService<AccountController>();
            //controller.ControllerContext = new ControllerContext(this.Request.RequestContext, controller);
            //ActionInvoker.InvokeAction(controller.ControllerContext, "LogOut");

            return RedirectToRoute(new
            {
                controller = "Account",
                action ="Logout",
            });
        }
    }
}

InjectsenseCore/Controllers/ManageMyPatientsController.cs
// ************************************************************
// Copyright (C) 2018 Injectsense, Inc. - All Rights Reserved
// ************************************************************
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Injectsense.Helpers;
using Injectsense.DataAccess.Repositories;
using Injectsense.DataAccess.Entities;
using Injectsense.DataAccess;
using Injectsense.Models;
using TimeZoneConverter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using System.Security.Claims;

namespace Injectsense.Controllers
{
    [Authorize]
    [OutputCache(Duration = 0)]
    public class ManageMyPatientsController : Controller
    {
        IUnitOfWork Transaction { get; }
        IClinicRepository ClinicRepository { get; }
        IPatientRepository PatientRepository { get; }
        ITransmissionRepository TransmissionRepository { get; }
        IDeviceRepository DeviceRepository { get; }

        private readonly IServiceProvider Services;

        public ManageMyPatientsController(IUnitOfWork unitOfWork,
                                          IClinicRepository clinicRepository, 
                                          IPatientRepository patientRepository,
                                          ITransmissionRepository transmissionRepository, 
                                          IDeviceRepository deviceRepository,
                                          IServiceProvider services)
        {
            Transaction = unitOfWork;
            ClinicRepository = clinicRepository;
            PatientRepository = patientRepository;
            TransmissionRepository = transmissionRepository;
            DeviceRepository = deviceRepository;

            Services = services;
        }

        // GET: ManageMyPatients
        public ActionResult Index()
        {
            MainContext mainContext = Services.GetRequiredService<MainContext>();

            // We could put the clinic id in the html and get it back on this call.
            // But the goal is to leave as little info as possible in html.
            // So let's get user and map to their clinic, and from clinic, we'll get list of patients.
            ClaimsPrincipal currentUser = this.User;
            string currentUserName = currentUser.FindFirst(ClaimTypes.Name).Value;

            (Guid ClinicId, Guid ClinicStaffId, string ClinicName, string ClinicStaffFirstName, string ClinicStaffLastName) clinicInfo  = ClinicStaffHelper.GetUsersClinicIdFromRequest(currentUserName, mainContext);

            // Get the list of patients for the clinic.
            List<Patient> patientList = ClinicRepository.GetAllPatients(clinicInfo.ClinicId);

            // Get the TimeZone info for the clinic.
            string localTimeZoneInfo = ClinicRepository.GetClinicDotNetTimeZoneInfo(clinicInfo.ClinicId);
            TimeZoneInfo timeZoneInfo = TZConvert.GetTimeZoneInfo(localTimeZoneInfo);

            // Get the patients that have transmission information.
            // List<ClinicPatientAssociation> ClinicPatientInfoList = ClinicRepository.GetAllPatientsWithNewTransmissionsForClinic(clinicInfo.ClinicId);

            // Create a view model and populate it.
            ManageMyPatientsModel model = new ManageMyPatientsModel();
            model.Initialize(currentUserName, mainContext);

            foreach (Patient p in patientList)
            {
                ClinicPatientAssociation cpa = ClinicRepository.GetClinicPatientAssociation(clinicInfo.ClinicId, p.Id);
                (Guid DeviceId, string ImplantEye, DateTime? ImplantDate) leftEyeInfo = PatientRepository.GetImplantedDeviceInfo(cpa.MostRecentTransmissionLeftEyeDSN);
                (Guid DeviceId, string ImplantEye, DateTime? ImplantDate) rightEyeInfo = PatientRepository.GetImplantedDeviceInfo(cpa.MostRecentTransmissionRightEyeDSN);

                // TODO: Need to handle case where there are no devices or 1 device.
                // Need to set a flag in model that left and/or right devices are not available.
                bool hasSensorInLeftEye = !Guid.Empty.Equals(leftEyeInfo.DeviceId);
                bool hasSensorInRightEye = !Guid.Empty.Equals(rightEyeInfo.DeviceId);

                DateTime lastReceivedDateTimeLocalized;
                string lastReceivedDateTimeLocalizedString;
                if (cpa.MostRecentTransmissionReceivedDateUTC.HasValue)
                {
                    lastReceivedDateTimeLocalized = TimeZoneInfo.ConvertTimeFromUtc(cpa.MostRecentTransmissionReceivedDateUTC.Value, timeZoneInfo);
                    lastReceivedDateTimeLocalizedString = lastReceivedDateTimeLocalized.ToString("dd-MMM-yyyy h:mm tt");
                }
                else
                {
                    lastReceivedDateTimeLocalizedString = "";
                }

                // Take into account Last Office Visit may be null.
                DateTime? lastOfficeVisit = ClinicRepository.GetLastOfficeVisitDate(clinicInfo.ClinicId, p.Id);
                string lastOfficeVisitString;
                if (lastOfficeVisit.HasValue)
                {
                    lastOfficeVisitString = lastOfficeVisit.Value.ToString("dd-MMM-yyyy");
                }
                else
                {
                    lastOfficeVisitString = "";
                }

                model.PatientList.Add(new ManageMyPatientInfo
                {
                    MostRecentTransmissionId = cpa.MostRecentTransmissionId,
                    PatientName = p.NameLast + ", " + p.NameFirst,
                    PatientId = p.Id,
                    DateOfBirthString = p.DateOfBirthNotUTC.ToString("dd-MMM-yyyy"),
                    LastReceivedTimestampString = lastReceivedDateTimeLocalizedString,
                    IdNumber = p.Identifier,
                    LeftEyeSerialNumber = hasSensorInLeftEye ? cpa.MostRecentTransmissionLeftEyeDSN : "",
                    RightEyeSerialNumber = hasSensorInRightEye ? cpa.MostRecentTransmissionRightEyeDSN : "",
                    LastOfficeVisitString = lastOfficeVisitString,
                    TotalNumberOfTransmissions = cpa.ViewableTransmissionCount,
                });
            }

            return View(model);
        }

        public ActionResult LogOut()
        {
            // This action/method is a kludge because I couldn't get the "sign out" link to change form Home/Logout to Account/Logout.
            // So this method is located here to call the LogOut action on the AccountController.

            // TODO: Remove after successful port to ASP.NET core.
            //var controller = DependencyResolver.Current.GetService<AccountController>();
            //controller.ControllerContext = new ControllerContext(this.Request.RequestContext, controller);
            //ActionInvoker.InvokeAction(controller.ControllerContext, "LogOut");

            return RedirectToRoute(new
            {
                controller = "Account",
                action = "Logout",
            });
        }
    }
}

InjectsenseCore/Views/Shared/_Layout.cshtml
@model Injectsense.Models.ModelBase

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Injectsense Demo</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link rel="stylesheet" href="~/lib/jquery-ui-combined/css/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <!--  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.css" /> -->
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-ui"></script>
    <script src="~/lib/modernizr"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/respond.js/respond.js"></script>

    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
            var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;)r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: 'c062ce49-96f0-4dc9-a74c-d40d7a3f4a75'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <img class="img-fluid" src="@Url.Content("~/images/logo.png")" alt="Image" style="width:250px;height:77px;" />

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav nav-fill w-100">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link", @style = "margin-top:25px;" })</li>
                    <li class="nav-item">@Html.ActionLink("Manage My Patients", "Index", "ManageMyPatients", null, new { @class = "nav-link", @style = "margin-top:25px;" })</li>
                    <li class="nav-item">@Html.ActionLink("Manage My Clinic", "Index", "ManageMyClinic", null, new { @class = "nav-link", @style = "margin-top:25px;" })</li>
                    <li class="nav-item d-none d-sm-block">
                        <div class="row float-right" style="text-align:center;">
                            <img class="nav-item" src="@Url.Content("~/images/StaffProfile2.png")" alt="Image" style="width:65px;height:65px;max-width:65px;max-height:65px;margin-top:15px;" />
                            <a class="nav-link disabled" style="color:black; width:100px; margin-top:10px;"><div style="text-align:center; width:100px;"><div class="d-inline-block text-truncate" style="text-align:center; width:100px;">@Model.LoggedInUserFirstName</div><div class="d-inline-block text-truncate" style="text-align:center; width:100px;">@Model.LoggedInUserLastName</div></div></a>
                        </div>
                    </li>
                    <li class="nav-item float-right">
                        @Html.ActionLink("Sign out", "LogOut", "Home", new { @class = "nav-link float-right", @style = "margin-top:25px;" })
                    </li>
                </ul>
            </div>
        </nav>
        <hr style="margin-top:2px;">
    </div>
    <div class="container body-content">
        @RenderBody()
        <br />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Injectsense, Inc.</p>
        </footer>
    </div>

    <script src="~/bundles/jquery"></script>
    <script src="~/bundles/jqueryui"></script>
    <script src="~/bundles/bootstrap"></script>

    @RenderSection("scripts", required: false)

    <!-- The following needs to load last -->
    <!-- add logic to provide image next to date picker -->
    <script type="text/javascript">
        $(function () {
            $('.datepicker').datepicker({
                dateFormat: "dd-M-yy",
                showOn: "button",
                buttonImage: "/images/if_calendar_115762_32x32.png",
                buttonImageOnly: true,
                buttonText: "Select date"
            });
            $(".trigger").click(function () {
                $(".datepicker").datepicker("show");
            });
        });
    </script>
    <!-- add logic to save the tab on refresh -->
    <script type="text/javascript">
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            localStorage.setItem('activeTab', $(e.target).attr('href'));
        });

        var activeTab = localStorage.getItem('activeTab');
        if (activeTab) {
            $('.nav-tabs a[href="' + activeTab + '"]').tab('show');
        }
    </script>
</body>
</html>